//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_phatthuong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChauNho
    {
        public int MaChau { get; set; }
        public Nullable<int> MaHo { get; set; }
        public string TenChau { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string Tentruong { get; set; }
        public string Lop { get; set; }
        public string ThanhTich { get; set; }
    
        public virtual HoGiaDinh HoGiaDinh { get; set; }
    }
}
