//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_phatthuong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoGiaDinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoGiaDinh()
        {
            this.ChauNhoes = new HashSet<ChauNho>();
            this.PhanPhois = new HashSet<PhanPhoi>();
        }
    
        public int MaHo { get; set; }
        public string TenHo { get; set; }
        public string DiaChi { get; set; }
        public string sdt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChauNho> ChauNhoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanPhoi> PhanPhois { get; set; }
    }
}
