//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_phatthuong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQua
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhanQua()
        {
            this.PhanPhois = new HashSet<PhanPhoi>();
        }
    
        public int MaQua { get; set; }
        public string TenQua { get; set; }
        public string MoTa { get; set; }
        public Nullable<decimal> GiaTri { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanPhoi> PhanPhois { get; set; }
    }
}
