//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_phatthuong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanPhoi
    {
        public int MaPhanPhoi { get; set; }
        public Nullable<System.DateTime> NgayPhanPhoi { get; set; }
        public Nullable<int> MaHo { get; set; }
        public Nullable<int> MaQua { get; set; }
        public Nullable<int> MaThuong { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual HoGiaDinh HoGiaDinh { get; set; }
        public virtual PhanQua PhanQua { get; set; }
        public virtual PhanThuong PhanThuong { get; set; }
    }
}
