//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_phatthuong.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLPTEntities : DbContext
    {
        public QLPTEntities()
            : base("name=QLPTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChauNho> ChauNhoes { get; set; }
        public virtual DbSet<HoGiaDinh> HoGiaDinhs { get; set; }
        public virtual DbSet<PhanPhoi> PhanPhois { get; set; }
        public virtual DbSet<PhanQua> PhanQuas { get; set; }
        public virtual DbSet<PhanThuong> PhanThuongs { get; set; }
    }
}
